### ISSUE TITLE
Cannot process a text file

### ISSUE THREAD

**Issue by Amnish04** [Namatuzio/tiller#10]
When trying to process a single file to generate html, the program throws an error suggesting its not a text file.
```
python .\main.py .\examples\example2.txt
```
![image](https://github.com/Namatuzio/tiller/assets/78865303/24e92c72-d848-4f06-869d-7b3643f3a7d3)

**Suggestion:**

The way you are checking for file extension could cause potential bugs
![image](https://github.com/Namatuzio/tiller/assets/78865303/4c3554fc-630c-44c1-a02a-e71afd2db391)
as there could be multiple dots in the file name.

Instead use
```
if(file.split(".")[-1] == "txt"):
```
Use **-1** index instead of **1**.

**Comment by Namatuzio** [comment]
Ah strange, I could've sworn I had this in an earlier version, nonetheless, thanks for the catch. Fixed.
