### ISSUE TITLE
Add TOML config feature

### ISSUE THREAD

**Issue by Amir-Helali** [Namatuzio/tiller#19]
I'd like to add the option to let the users use a TOML config file so that they can have all their inputs int it instead of providing individual arguments when running the program. This feature will use -c or --config and accepts a TOML config file path.

**Comment by Namatuzio** [comment]
Sounds great, I'll assign it to you to work on it.

**Comment by Amir-Helali** [comment]
@Namatuzio  I finished implementing and testing the feature, and created a pull request for you to review.
