### ISSUE TITLE
Formatting issues in Readme.md

### ISSUE THREAD

**Issue by Amnish04** [Namatuzio/tiller#6]
I noticed some formatting issues in the README file.

![image](https://github.com/Namatuzio/tiller/assets/78865303/69f0b348-b234-43d7-8dfc-1f262d66a633)

**Issues:**

1. The hierarchy of headings doesn't seem right. For example, `### Features` could be changed to `## Features` for a better structure.
2. Installation instructions could be written as a number list for better clarity.
3. Code samples should be in triple backticks for more readable and accessible code blocks like so.

`code sample` ❌

```
code sample ✔️
```

**Comment by Amnish04** [comment]
@Namatuzio I've opened a pull request to change the instructions to a numbered list for you. You can review and decide if you want to merge the changes in

[Pull Request](https://github.com/Namatuzio/tiller/pull/7)

**Comment by Namatuzio** [comment]
It was a simple change, thanks for the recommendation I do agree it does make it easier.
