### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by Amnish04** [Namatuzio/tiller#8]
@Namatuzio  I know you might be working on this, but this will act as a reminder for you.

Adding a `requirements.txt` file will make it easier for newcomers to know what dependencies your project uses and instead of downloading each dependency manually, all dependencies can be installed with a single command like so:
```
pip install -r requirements.txt
```

Here's what a `requirements.txt` file could look like:
```
# You can specify exact package versions
package-name==1.2.3

# You can use comparison operators for version ranges
another-package>=2.0.0,<3.0.0

# You can also specify packages without version constraints
third-package

# You can include comments by starting a line with #
# Optional package for development and testing
dev-package>=0.1.0

# You can specify URLs or VCS repositories for packages
git+https://github.com/user/repo.git@branch-name
```

Its very similar to what a `package.json` does in node projects.

**Comment by Namatuzio** [comment]
Yep, I was working on it but got interrupted due to some personal stuff. Thanks for the explanation, though I do know how it works already.
