### ISSUE TITLE
Invalid Dependency documented in README

### ISSUE THREAD

**Issue by Amnish04** [Namatuzio/tiller#9]
I tried installing the dependencies of the project based on the info provided in `README.md`.

However, when trying to install `type[all]`, I got an error

![image](https://github.com/Namatuzio/tiller/assets/78865303/49c57a66-5969-438f-863b-a4dab373045a)

I later realized it was misspelled and should be `typer[all]` instead. (as you mentioned on slack)

**Comment by Namatuzio** [comment]
Fixed up, thanks for the catch.
